### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by pmin825** [pmin825/BidUp#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [ ] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jenvomo** [comment]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by jenvomo** [comment]
Great job @pmin825 ! Really coming along! 

One thing on functionality is that when switching between the routes for login and signup using the link on the modal, the modal goes away and renders a full page.  I would update this so the modal stays open and the form on the modal changes.

Additionally, styling on the modal could use a little tweaking. Theres a lot of whitespace at the top of the form, the inputs are super tall and the links font isn't the same as the nice modern font you have on everything else.

**Comment by jenvomo** [comment]
Great job! Last couple things:
- [x] Fix font on error message on session form

Suggestions:
- Remove border on buttons on the session form (looks cleaner without borders)
- Remove the glow on the buttons when you click on them (the blue outline)
- lighten up the grey border around the input fields
- Add a little more space between the last input field and the form button on session form
- Add a little padding inside the input boxes so that when you type in them, the text isn't so close to the edge of the box

**Comment by jenvomo** [comment]
Awesome updates @pmin825 ! 

Last suggestion would be to make sure the sign up form isn't getting wider when errors render.

**Comment by jenvomo** [comment]
Great job @pmin825 !
